export const HUBS = [
  {
    slug: 'igv',
    name: 'iGV Hub',
    fullName: 'Incoming Global Volunteer',
    accent: '#f85a40',
    emoji: '🌍',
    description: 'Resources, tools, and guides for the Incoming Global Volunteer portfolio. Find everything you need to deliver world-class volunteer exchange experiences across AIESEC India.',
    resources: [
      { title: 'iGV Standards & Processes', icon: '📋', type: 'drive', desc: 'Complete operational standards and processes for iGV delivery' },
      { title: 'EP Journey Framework', icon: '🗺️', type: 'slides', desc: 'End-to-end exchange participant journey mapping and touchpoints' },
      { title: 'iGV Matching Guide', icon: '🤝', type: 'doc', desc: 'Step-by-step guide to matching and managing exchange participants' },
      { title: 'Raising & Matching Tracker', icon: '📊', type: 'drive', desc: 'National tracker for raise, match, and realize metrics' },
      { title: 'OPS Manual 26.27', icon: '📖', type: 'pdf', desc: 'Official operational manual for the 26.27 term' },
      { title: 'Partner Communication Templates', icon: '✉️', type: 'drive', desc: 'Email and message templates for hosting partner communication' },
      { title: 'iGV Training Materials', icon: '🎓', type: 'slides', desc: 'National LC training decks for iGV capacity building' },
      { title: 'Quality Standards Checklist', icon: '✅', type: 'doc', desc: 'Minimum quality standards checklist for iGV projects' },
    ],
  },
  {
    slug: 'ogv',
    name: 'oGV Hub',
    fullName: 'Outgoing Global Volunteer',
    accent: '#f85a40',
    emoji: '✈️',
    description: 'Everything your LC needs to send Indian youth on transformational volunteer experiences abroad. Access sign-up tools, preparation guides, and EP management resources.',
    resources: [
      { title: 'oGV Sign-up Campaign Kit', icon: '📣', type: 'drive', desc: 'Social media assets and campaign materials for oGV sign-up drives' },
      { title: 'EP Preparation Guide', icon: '🧳', type: 'doc', desc: 'Pre-departure guide for outgoing exchange participants' },
      { title: 'Country Intelligence Reports', icon: '🌐', type: 'slides', desc: 'Country profiles and exchange intelligence for top destinations' },
      { title: 'oGV Conversion Playbook', icon: '🎯', type: 'slides', desc: 'Strategies and scripts for converting sign-ups to matched EPs' },
      { title: 'oGV Tracker 26.27', icon: '📈', type: 'drive', desc: 'National oGV performance and pipeline tracker' },
      { title: 'EP Management SOP', icon: '📋', type: 'doc', desc: 'Standard operating procedures for managing oGV participants' },
    ],
  },
  {
    slug: 'igtae',
    name: 'iGTae Hub',
    fullName: 'Incoming Global Talent & Exchange',
    accent: '#0CB9C1',
    emoji: '💼',
    description: 'Hub for managing incoming global talent and professional exchange programmes. Access JD templates, partner management tools, and quality delivery frameworks.',
    resources: [
      { title: 'JD Template Library', icon: '📝', type: 'drive', desc: 'Approved job description templates across all project types' },
      { title: 'iGTae Standards Manual', icon: '📚', type: 'pdf', desc: 'Complete standards for iGTae project delivery and quality' },
      { title: 'Partner Onboarding Kit', icon: '🤝', type: 'slides', desc: 'Onboarding materials and pitch deck for new hosting partners' },
      { title: 'iGTae Matching Tracker', icon: '📊', type: 'drive', desc: 'Live tracker for raise, match, and realize pipeline' },
      { title: 'EP Experience Guide', icon: '🌟', type: 'doc', desc: 'Framework for delivering exceptional EP experiences' },
      { title: 'Invoice & Contract Templates', icon: '📄', type: 'drive', desc: 'Standardised financial and legal document templates' },
    ],
  },
  {
    slug: 'ogtae',
    name: 'oGTae Hub',
    fullName: 'Outgoing Global Talent & Exchange',
    accent: '#0CB9C1',
    emoji: '🚀',
    description: 'Resources for sending Indian talent on professional exchange experiences globally. Includes application guides, skill-matching tools, and pre-departure frameworks.',
    resources: [
      { title: 'oGTae Application Toolkit', icon: '📋', type: 'drive', desc: 'Application forms, CV templates, and guidance documents' },
      { title: 'Skills Matching Framework', icon: '🎯', type: 'slides', desc: 'Framework for matching EP skills to available opportunities' },
      { title: 'Pre-departure Checklist', icon: '✅', type: 'doc', desc: 'Comprehensive checklist for outgoing talent preparation' },
      { title: 'Alumni Testimonials Deck', icon: '💬', type: 'slides', desc: 'Impact stories and testimonials from oGTae alumni' },
      { title: 'oGTae Pipeline Tracker', icon: '📈', type: 'drive', desc: 'LC-level pipeline and performance tracker' },
    ],
  },
  {
    slug: 'mkt',
    name: 'MKT Hub',
    fullName: 'Marketing',
    accent: '#037ef3',
    emoji: '📣',
    description: 'Brand assets, campaign toolkits, social media guidelines, and marketing resources for AIESEC India LCs. Maintain brand consistency and amplify your local impact.',
    resources: [
      { title: 'Brand Guidelines 26.27', icon: '🎨', type: 'pdf', desc: 'Official AIESEC India brand guidelines for the 26.27 term' },
      { title: 'Social Media Asset Library', icon: '🖼️', type: 'drive', desc: 'Ready-to-use graphics and templates for all platforms' },
      { title: 'Campaign Calendar 26.27', icon: '📅', type: 'slides', desc: 'National marketing calendar with key campaign dates and themes' },
      { title: 'Canva Template Hub', icon: '✏️', type: 'link', desc: 'Access all approved Canva design templates' },
      { title: 'Content Strategy Playbook', icon: '📋', type: 'doc', desc: 'Content strategy, tone of voice, and posting guidelines' },
      { title: 'Photo & Video Bank', icon: '📸', type: 'drive', desc: 'Approved photography and video assets for LCs' },
      { title: 'PR & Media Kit', icon: '📰', type: 'drive', desc: 'Press release templates and media outreach resources' },
    ],
  },
  {
    slug: 'bd',
    name: 'BD Hub',
    fullName: 'Business Development',
    accent: '#ffc845',
    emoji: '🤝',
    description: 'Sales tools, partnership frameworks, and BD playbooks to help LCs raise more opportunities and grow your hosting network. Drive revenue and impact together.',
    resources: [
      { title: 'BD Pitch Deck Template', icon: '📊', type: 'slides', desc: 'National-standard pitch deck for prospecting new partners' },
      { title: 'Partnership Agreement Templates', icon: '📄', type: 'doc', desc: 'Standardised partnership and MoU templates' },
      { title: 'Prospecting & CRM Guide', icon: '🎯', type: 'slides', desc: 'CRM setup and systematic prospecting methodology' },
      { title: 'BD Training Modules', icon: '🎓', type: 'drive', desc: 'Sales and BD training resources for LC team upskilling' },
      { title: 'National BD Tracker 26.27', icon: '📈', type: 'drive', desc: 'Live BD pipeline and opportunity tracker across all LCs' },
      { title: 'Success Stories & Case Studies', icon: '⭐', type: 'slides', desc: 'Impact cases and success stories to use in partner meetings' },
    ],
  },
  {
    slug: 'pm',
    name: 'PM Hub',
    fullName: 'People Management',
    accent: '#7552CC',
    emoji: '👥',
    description: 'Recruitment, onboarding, culture, and member development resources. Everything you need to attract, grow, and retain an exceptional AIESEC team at your LC.',
    resources: [
      { title: 'Recruitment Toolkit 26.27', icon: '📣', type: 'drive', desc: 'Application forms, interview guides, and recruitment campaign kits' },
      { title: 'Member Onboarding Flow', icon: '🎉', type: 'slides', desc: 'National onboarding journey and induction programme framework' },
      { title: 'Performance Management Guide', icon: '📊', type: 'doc', desc: 'Goal-setting, review cycles, and performance management framework' },
      { title: 'Culture & Wellbeing Toolkit', icon: '💜', type: 'drive', desc: 'Culture-building activities, check-in tools, and wellbeing resources' },
      { title: 'Learning & Development Calendar', icon: '📅', type: 'slides', desc: 'National L&D programme schedule and resources' },
      { title: 'Offboarding & Alumni Guide', icon: '🌟', type: 'doc', desc: 'Member offboarding process and alumni engagement framework' },
    ],
  },
  {
    slug: 'fnl',
    name: 'FnL Hub',
    fullName: 'Finance & Legal',
    accent: '#00c16e',
    emoji: '💰',
    description: 'Financial templates, legal compliance resources, and budget planning tools for AIESEC India LCs. Manage your finances with accuracy and maintain full legal compliance.',
    resources: [
      { title: 'Budget Planning Template', icon: '💹', type: 'drive', desc: 'Annual and term-wise budget planning templates for LCs' },
      { title: 'Financial Report Format', icon: '📊', type: 'doc', desc: 'Standardised financial reporting format for national submission' },
      { title: 'Invoice & Receipt Templates', icon: '🧾', type: 'drive', desc: 'Approved invoice, receipt, and expense reimbursement templates' },
      { title: 'GST & Compliance Guide', icon: '📋', type: 'pdf', desc: 'GST obligations, compliance checklist, and filing guidance for LCs' },
      { title: 'MoU & Contract Library', icon: '📄', type: 'drive', desc: 'Legal document templates reviewed by national legal team' },
      { title: 'Audit Preparation Checklist', icon: '✅', type: 'doc', desc: 'Checklist and guidance for internal and external audits' },
    ],
  },
  {
    slug: 'expansions',
    name: 'Expansions',
    fullName: 'Expansions',
    accent: '#9b1c1c',
    emoji: '🚀',
    description: 'Resources and tools for AIESEC India expansion initiatives.',
    resources: [],
  },
];

export function getHub(slug) {
  return HUBS.find((h) => h.slug === slug) ?? null;
}

export const STATIC_PAGES = {
  'aiesec-way': {
    title: 'The AIESEC Way',
    subtitle: 'The philosophy, values, and vision that guide every AIESEC member worldwide.',
    accent: '#037ef3',
    sections: [
      {
        heading: 'Our Vision',
        body: 'Peace and fulfillment of humankind\'s potential. This vision drives every exchange, every leadership opportunity, and every decision we make as an organisation. AIESEC exists to create a positive impact on society through developing leadership in young people.',
        image: 'https://picsum.photos/seed/vision/800/400',
      },
      {
        heading: 'Our Mission',
        body: 'To engage and develop every young person in the world. We do this by providing the platform for cross-cultural exchange and leadership development opportunities. Through our programmes, young people develop the leadership qualities needed to become positive change agents.',
        image: 'https://picsum.photos/seed/mission/800/400',
      },
      {
        heading: 'Our Values',
        body: 'Activating Leadership, Demonstrating Integrity, Living Diversity, Enjoying Participation, Striving for Excellence, and Acting Sustainably. These six values are the foundation of everything we do — from how we run meetings to how we deliver exchanges.',
        image: null,
      },
    ],
    resources: [
      { title: 'AIESEC Way', icon: '📖', type: 'pdf', desc: 'The complete AIESEC Way framework and values guide' },
      { title: 'Leadership Development Model', icon: '🌟', type: 'slides', desc: 'AIESEC\'s leadership development framework' },
      { title: 'Values Integration Guide', icon: '💡', type: 'doc', desc: 'How to embed AIESEC values into your LC culture and operations' },
    ],
  },
  'global-academies': {
    title: 'Global Academies',
    subtitle: 'Learning experiences, leadership academies, and global development programmes for AIESEC members.',
    accent: '#00c16e',
    sections: [
      {
        heading: 'What are Global Academies?',
        body: 'Global Academies are structured learning experiences designed to accelerate the development of AIESEC leaders. These programmes bring together top talent from across the network for intensive learning, cross-cultural exchange, and collaborative projects that create real-world impact.',
        image: 'https://picsum.photos/seed/academy/800/400',
      },
      {
        heading: 'Programme Offerings',
        body: 'From national leadership academies to global summits, AIESEC offers a range of learning programmes at every stage of your membership journey. Each programme is designed around AIESEC\'s leadership development model and values framework.',
        image: 'https://picsum.photos/seed/programme/800/400',
      },
      {
        heading: 'How to Apply',
        body: 'Global Academies have defined application cycles each term. Check with your LC PM team for current opportunities. Selection is based on your leadership profile, exchange experience, and current role within AIESEC.',
        image: null,
      },
    ],
    resources: [
      { title: 'Global Academy Catalogue 26.27', icon: '📚', type: 'slides', desc: 'Full list of available academies and programmes this term' },
      { title: 'Application Guidelines', icon: '📋', type: 'doc', desc: 'How to apply and what to expect from the selection process' },
      { title: 'Academy Alumni Stories', icon: '💬', type: 'slides', desc: 'Impact stories from past Global Academy participants' },
    ],
  },
  'conference-output': {
    title: 'Conference Output',
    subtitle: 'Key outputs, presentations, decisions, and resources from national and regional AIESEC India conferences.',
    accent: '#f59e0b',
    sections: [
      {
        heading: 'Lorem Ipsum Conferences',
        body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        image: 'https://picsum.photos/seed/conference/800/400',
      },
    ],
    resources: [
      { title: 'Placeholder Output Deck', icon: '🎤', type: 'slides', desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod' },
      { title: 'Placeholder Facilitator Guides', icon: '📋', type: 'drive', desc: 'Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi' },
      { title: 'Placeholder Session Materials', icon: '📂', type: 'drive', desc: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum' },
      { title: 'Placeholder Conference Outputs', icon: '🗺️', type: 'drive', desc: 'Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia' },
      { title: 'Placeholder Planning Templates', icon: '📝', type: 'doc', desc: 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium' },
      { title: 'Placeholder Recordings', icon: '🎥', type: 'drive', desc: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit' },
    ],
  },
};

export const RNR_LEADERBOARD = [
  { rank: 1,  lc: 'AIESEC in Manipal',    points: 1 },
  { rank: 2,  lc: 'AIESEC in Delhi-IIT',  points: 1 },
  { rank: 3,  lc: 'AIESEC in Pune',       points: 1 },
  { rank: 4,  lc: 'AIESEC in Mumbai',     points: 1 },
  { rank: 5,  lc: 'AIESEC in Bangalore',  points: 1 },
  { rank: 6,  lc: 'AIESEC in Hyderabad',  points: 1 },
  { rank: 7,  lc: 'AIESEC in Chennai',    points: 1 },
  { rank: 8,  lc: 'AIESEC in Kolkata',    points: 1 },
  { rank: 9,  lc: 'AIESEC in Ahmedabad',  points: 1 },
  { rank: 10, lc: 'AIESEC in Jaipur',     points: 1 },
  { rank: 11, lc: 'AIESEC in Chandigarh', points: 1 },
  { rank: 12, lc: 'AIESEC in Kochi',      points: 1 },
  { rank: 13, lc: 'AIESEC in Lucknow',    points: 1 },
  { rank: 14, lc: 'AIESEC in Nagpur',     points: 1 },
  { rank: 15, lc: 'AIESEC in Bhopal',     points: 1 },
];
